<?xml version="1.0"?>
<package format="3">
  <name>media_play</name>
  <version>2.0.0</version>
  <description>ROS 2 video playback, subtitle and upload service.</description>
  <maintainer email="yl.wang@zj-humanoid.com">wangyulong</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>media_play_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>mpv</exec_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
